---
version: "2.0"

services:
  app:
    image: dimokus88/ubuntu:1.1
    env:
#1.Раздел часной информации, неделитесь даннмы из этого раздела!
#1.Private information section, do not share data from this section!Раздел часной информации, неделитесь даннмы из этого раздела!
     - "my_root_password=" # пароль root для подключения по ssh
     - "MONIKER=Name_Akash" #Node name (Extra tokens ACRE to write "Akash" in moniker, example: Dimokus_Akash). Имя ноды (Дополнительный токены ACRE за "Akash" в моникере, например:DimokusAkash).
     - "MNEMONIC=" # seed фраза от тестового кошелька
     - "LINK_KEY=" # link to the posted pirv-validator_key.json (direct download). It will also work from other Cosmos-based testnets.Ссылка на размещенный pirv-validator_key.json (прямое скачивание). Подойдет и от других тестнетов на базе Cosmos.
#==================================================================
#2.Раздел переменных для работы ноды
#2.Section of variables for node operation   
     - "validator_node=yes"
     - "autodelegate=no"
     - "binary=acred"
     - "vers=testnet_bamboo"
     - "genesis=https://raw.githubusercontent.com/ArableProtocol/acrechain/testnet_bamboo/networks/bamboo/genesis.json"
     - "folder=.acred"
     - "denom=uacre"
     - "chain=bamboo_9000-1"
     - "gitrep=https://github.com/ArableProtocol/acrechain.git"
     - "gitfold=acrechain"
     - "SHIFT=4000"
     - "PEER=6d41af54405fa98073b178262ec9d083b3f12e67@46.4.81.204:36656,464de18a87cdfd0735ba8bf9195db51ce78f5ef3@49.12.236.218:46656,1ea1c9b05deb07d8642977e0f3746efbbe456d49@202.61.229.238:26656,a59e9ae33891766879ecef8d6f91a72369048eef@provider.europlots.com:31073,44dd124ca34742245ad906f9f6ea377fae3af0cf@168.100.9.100:26656,6477921cdd4ba4503a1a2ff1f340c9d6a0e7b4a0@168.100.10.133:26656,9b53496211e75dbf33680b75e617830e874c8d93@168.100.8.9:26656,c55d79d6f76045ff7b68dc2bf6655348ebbfd795@168.100.8.60:26656"
     - "SNAP_RPC=http://provider.europlots.com:32099"  
    command:
      - "bash"
      - "-c"
    args:
      - 'curl -s https://raw.githubusercontent.com/Dimokus88/universe/main/alphatest/node.sh | bash '
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 22
        as: 22
        to:
          - global: true
      - port: 26656
        as: 26656
        to:
          - global: true
      - port: 26657
        as: 26657
        to:
          - global: true
        
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 2.0
        memory:
          size: 4Gi
        storage:
          size: 100Gi
        
        
  placement:
    akash: 
      attributes:
            
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 
