---
version: "2.0"

services:
  app:
    image: dimokus88/ubuntu:1.1
    env:
#1.Раздел часной информации, неделитесь даннмы из этого раздела!
#1.Private information section, do not share data from this section!
      - "my_root_password=" # Root password far a ssh connection. Пароль root для подключения по ssh.
      - "MONIKER=" # Node name. Use "Akash" in moniker(for example: Dimokus_Akash) to help develop the project! Имя ноды. Используйте в моникере "Akash"(например: Dimokus_Akash) что бы помочь в развитии проекта!
      - "LINK_KEY=" # link to the posted pirv-validator_key.json (direct download). It will also work from other Cosmos-based testnets.Ссылка на размещенный pirv-validator_key.json (прямое скачивание). Подойдет и от других тестнетов на базе Cosmos.
#==================================================================
#2.Раздел переменных для работы ноды
#2.Section of variables for node operation"
     - "binary=acred"
     - "vers=testnet_bamboo"
     - "genesis=https://raw.githubusercontent.com/ArableProtocol/acrechain/testnet_bamboo/networks/bamboo/genesis.json"
     - "folder=.acred"
     - "denom=uacre"
     - "chain=bamboo_9000-1"
     - "gitrep=https://github.com/ArableProtocol/acrechain.git"
     - "gitfold=acrechain"
     - "SHIFT=4000"
     - "link_peer=https://raw.githubusercontent.com/Dimokus88/Acrechain/main/PEER"
     - "SNAP_RPC=http://49.12.236.218:46657"  
    command:
      - "bash"
      - "-c"
    args:
      - 'curl -s https://raw.githubusercontent.com/Dimokus88/universe/main/main.sh | bash '
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 22
        as: 22
        to:
          - global: true
      - port: 26656
        as: 26656
        to:
          - global: true
      - port: 26657
        as: 26657
        to:
          - global: true
        
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 2.0
        memory:
          size: 4Gi
        storage:
          size: 100Gi
        
        
  placement:
    akash: 
      attributes:
            
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 
